<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLIoamBJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLIoamBJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLIoamBJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLIoamBJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLIoamBJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'LIoamBJ',
    'container.build_id' => '241d9219',
    'container.build_time' => 1728898518,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLIoamBJ');
